#ifndef OBCS_OPTIONS_H
#define OBCS_OPTIONS_H
#include "PACKAGES_CONFIG.h"
#include "CPP_OPTIONS.h"

#ifdef ALLOW_OBCS
#undef ALLOW_OBCS_NORTH
#undef ALLOW_OBCS_SOUTH
#undef ALLOW_OBCS_EAST
#undef ALLOW_OBCS_WEST

#undef ALLOW_ORLANSKI
#undef ALLOW_OBCS_PRESCRIBE
#undef ALLOW_OBCS_STEVENS
#undef ALLOW_OBCS_SPONGE
#undef ALLOW_OBCS_BALANCE
#undef ALLOW_OBCS_TIDES

#endif /* ALLOW_OBCS */
#endif /* OBCS_OPTIONS_H */
